Pg repository migration sg
4teamwork/opengever.maintenance pull request #240
Opened 2020-12-17 12:04 UTC by njohner

2020-12-17 16:02 UTC, njohner reviewed
🎉 nice

2020-12-17 16:02 UTC, njohner commented on opengever/maintenance/scripts/repository_migration_analyse.py
> +    def validate(self):
is not called anywhere yet

2020-12-18 07:33 UTC, njohner commented on opengever/maintenance/scripts/repository_migration_analyse.py
> +    def reindex(self):
Shouldn't we also reindex all children of moved objects? Maybe that happened automatically with the move

2020-12-23 10:32 UTC, njohner commented on opengever/maintenance/scripts/repository_migration_analyse.py
> +                # check if parent is already changed - so no need to change
It could be that both the parent has a new number and it itself has a new number.

2021-01-04 17:37 UTC, njohner commented on opengever/maintenance/scripts/repository_migration_analyse.py
> +            # Remove splitting dots - they're not usefull for comparing etc.
I added a check that the deployment uses grouped_by_three

2021-01-04 17:40 UTC, njohner commented on opengever/maintenance/scripts/repository_migration_analyse.py
> +            obj.reindexObject(idxs=['Title', 'sortable_title', 'path', 'reference'])
In solr `SearchableText` only contains the content from the blob

2021-01-08 13:02 UTC, buchi requested changes
LGTM!

I would ✂️  the `_analyse` part from the script filename.

As already discussed, doc properties are updated when moving repos.
I'm now trying out the migration with the full content of HBA...

2021-01-08 13:16 UTC, njohner commented on opengever/maintenance/scripts/repository_migration_analyse.py
> +    """In read-only mode, allow login of existing users without updating
Wops, copy-paste fail...

2021-01-08 13:19 UTC, njohner commented on opengever/maintenance/scripts/repository_migration_analyse.py
> +            self.build_xlsx_main_report(self.bundle)
No you're right, we make our own validation at the end.

2021-01-08 13:24 UTC, njohner commented on opengever/maintenance/scripts/repository_migration_analyse.py
> +class OperationItem(object):
True, it's either an existing or a future repository position. 👍

2021-01-08 14:09 UTC, njohner commented
Thanks for the review. I updated according to your comments.

2021-01-18 09:51 UTC, buchi approved these changes

2021-01-18 10:44 UTC, merged