Improve OS migration script
4teamwork/opengever.maintenance pull request #251
Opened 2021-02-19 11:30 UTC by njohner

- We allow setting new permissions on existing repository folders. Note that we only do this if inheritance is blocked and local_roles are indicated in the Excel. These will replace the existing sharing permissions
- We skip the docproperties update
- We add commits during the migration, this is a test to see whether it will make the migration faster.
- I also improved logging a bit.

Tests were also updated, see https://github.com/4teamwork/opengever.core/pull/6792

For https://4teamwork.atlassian.net/browse/CA-1472

2021-02-22 08:42 UTC, lukasgraf requested changes
LGTM 👍 , except the `commit()` not respecting the dryrun flag.

2021-02-22 08:42 UTC, lukasgraf commented on opengever/maintenance/scripts/repository_migration.py
> +        transaction.commit()
These should respect `options.dryrun`.

2021-02-22 11:36 UTC, njohner commented on opengever/maintenance/scripts/repository_migration.py
> +        transaction.commit()
True, thanks!

2021-02-22 14:29 UTC, njohner commented
All done. As discussed, the last commit will be tested in the next test-migration, see if it really speeds the migration up.

2021-02-22 14:31 UTC, lukasgraf approved these changes
LGTM 👍

2021-02-24 15:13 UTC, njohner commented
@lukasgraf can you have a look at the last commit? I had to exclude reindexing the SearchableText as we won't have the blobs during migration.

2021-02-25 10:12 UTC, lukasgraf approved these changes
LGTM 👍

2021-04-06 08:54 UTC, merged